name: Build Test
on:
  pull_request:
    branches:
      - develop
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Linter
        run: 'npm run lint'
      - name: Build
        run: 'npm run deploy'
