name: Dev Deploy
on:
  pull_request:
    branches:
      - develop
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: 'npm run build && npm run export'
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RAFAEL_ZASAS }}'
          projectId: rafael-zasas
          expires: 30d
          channelId: 'Beta'
          entrypoint: ./lib
          target: rtx rafaelzasas-next-react
