name: Dev Deploy
on:
  pull_request:
    branches:
      - develop
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Linter
        run: 'npm run lint'
      - name: Build
        run: 'npm run deploy'
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RAFAEL_ZASAS }}'
          projectId: rafael-zasas
          expires: 5d
          channelId: 'dev'
          target: rtx
